openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /kaimemo:
    get:
      summary: 買い物一覧取得
      description: 全件取得する
      responses:
        200: 
          $ref: '#/components/responses/GetKaimemos'
components:
  responses:
    GetKaimemos:
      description: 買い物一覧取得
      content:
        application/json:
          schema:
           $ref: '#/components/schemas/Kaimemo'
    UnauthorizedError:
      description: Access token is missing or invalid
    NotFoundError:
      description: The specified resource was not found
    GeneralError:
      description: Unexpected error
  schemas:
    Kaimemo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
        done:
          type: boolean
